---
- hosts: 54.226.90.70
  become: true
  tasks:
          - name: install apache2 on node1
            apt:
              update_cache: yes
          - name: install apache2
            apt: name=apache2 state=present
